### ISSUE TITLE
Cell Style Based on Cell Value

### ISSUE THREAD

**Issue by apoorva-sriv** [firegloves/MemPOI#68]
Is there a way to apply a cell style based on the cell value? For example, I have a column that should be right aligned if the cell value is not `null` and left aligned if it's `null`.

**Comment by firegloves** [comment]
Not currently, even if it is a planned improvement. 

You could manually loop on the resulting document in order to check the value and apply what you need, but If you want to keep the generation process atomic and avoid saving the document using mempoi and then open it manually and update it, I think you could leverage the data post elaboration pipeline. You could leave empty the `analysis` methods and enclose the whole logic inside the `execute` method

**Comment by apoorva-sriv** [comment]
Thanks. I'll try it out and update maybe on Tuesday.
